"""nflreadpy acquisition pipeline."""

from __future__ import annotations

import logging
import platform
import time
from collections.abc import Callable
from pathlib import Path
from typing import Any

import polars as pl

from nfl_fabric_acquisition.config import AcquisitionConfig
from nfl_fabric_acquisition.io import build_schema_manifest, ensure_dir, utc_now_iso, write_json
from nfl_fabric_acquisition.io import write_parquet
from nfl_fabric_acquisition.quality import validate_outputs

LOGGER = logging.getLogger(__name__)


Loader = Callable[[], pl.DataFrame]

DATASET_MIN_SEASONS = {
    "pbp": 1999,
    "schedules": 1999,
    "rosters": 1999,
    "rosters_weekly": 2002,
    "player_stats_weekly": 1999,
    "team_stats_weekly": 1999,
    "player_stats_reg": 1999,
    "team_stats_reg": 1999,
    "player_stats_post": 1999,
    "team_stats_post": 1999,
}


def seasons_for_dataset(seasons: list[int], dataset: str) -> list[int]:
    min_season = DATASET_MIN_SEASONS.get(dataset, min(seasons))
    return [season for season in seasons if season >= min_season]


def availability_notes(seasons: list[int]) -> dict[str, Any]:
    requested_start = min(seasons)
    notes = {}
    for dataset, min_season in DATASET_MIN_SEASONS.items():
        if requested_start < min_season:
            notes[dataset] = {
                "requested_start_season": requested_start,
                "available_start_season": min_season,
                "skipped_seasons": [
                    season for season in seasons if season < min_season
                ],
            }
    return notes


def configure_nflreadpy(cache_dir: Path) -> None:
    from nflreadpy.config import update_config

    update_config(
        cache_mode="filesystem",
        cache_dir=cache_dir,
        verbose=True,
        timeout=120,
        user_agent="fabric-nfl-analytics-local-acquisition",
    )


def load_with_retries(name: str, loader: Loader, *, retries: int) -> pl.DataFrame:
    last_error: Exception | None = None
    for attempt in range(1, retries + 1):
        try:
            LOGGER.info("Fetching %s (attempt %s/%s)", name, attempt, retries)
            return loader()
        except Exception as exc:  # pragma: no cover - exercised against network failures
            last_error = exc
            if attempt == retries:
                break
            sleep_seconds = min(2 ** attempt, 30)
            LOGGER.warning("%s failed: %s. Retrying in %ss.", name, exc, sleep_seconds)
            time.sleep(sleep_seconds)
    raise RuntimeError(f"Failed to fetch {name} after {retries} attempts") from last_error


def fetch_and_write(
    *,
    dataset: str,
    path,
    loader: Loader,
    config: AcquisitionConfig,
    season: int | None = None,
) -> dict[str, Any]:
    if path.exists() and not config.force:
        LOGGER.info("Skipping existing %s at %s", dataset, path)
        return write_parquet(
            pl.read_parquet(path),
            path,
            dataset=dataset,
            season=season,
            compression=config.compression,
            force=False,
        )

    df = load_with_retries(dataset if season is None else f"{dataset} {season}", loader, retries=config.retries)
    result = write_parquet(
        df,
        path,
        dataset=dataset,
        season=season,
        compression=config.compression,
        force=config.force,
    )
    LOGGER.info(
        "%s %s: %s rows, %s columns, %s",
        dataset,
        season if season is not None else "",
        result["rows"],
        result["columns"],
        result["status"],
    )
    return result


def write_local_readme(config: AcquisitionConfig) -> None:
    ensure_dir(config.out)
    text = f"""# nflverse local raw export

Generated by `nfl-fabric-acquisition`.

- Seasons: {config.start_season}-{config.end_season}
- Team focus for validation: {config.team_focus}
- Raw data is full-league and source-preserving.
- Manifests live in `manifest/`.
- Parquet files live in `raw/nflverse/`.
"""
    readme_path = config.out / "README.md"
    if config.force or not readme_path.exists():
        readme_path.write_text(text, encoding="utf-8")


def run_acquisition(config: AcquisitionConfig) -> dict[str, Any]:
    import nflreadpy as nfl

    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
    seasons = config.seasons

    ensure_dir(config.out)
    ensure_dir(config.cache)
    ensure_dir(config.manifest_dir)
    write_local_readme(config)
    configure_nflreadpy(config.cache)

    manifest: dict[str, Any] = {
        "fetched_at_utc": utc_now_iso(),
        "python_version": platform.python_version(),
        "platform": platform.platform(),
        "seasons": seasons,
        "team_focus": config.team_focus,
        "output_root": str(config.out),
        "cache_dir": str(config.cache),
        "compression": config.compression,
        "skip_optional": config.skip_optional,
        "availability_notes": availability_notes(seasons),
        "outputs": [],
    }

    for season in seasons:
        manifest["outputs"].append(
            fetch_and_write(
                dataset="pbp",
                season=season,
                path=config.pbp_path(season),
                loader=lambda season=season: nfl.load_pbp(season),
                config=config,
            )
        )

    manifest["outputs"].append(
        fetch_and_write(
            dataset="schedules",
            path=config.range_file_path(
                "schedules", f"schedules_{config.start_season}_{config.end_season}.parquet"
            ),
            loader=lambda: nfl.load_schedules(seasons),
            config=config,
        )
    )
    manifest["outputs"].append(
        fetch_and_write(
            dataset="teams",
            path=config.range_file_path("teams", "teams.parquet"),
            loader=nfl.load_teams,
            config=config,
        )
    )
    manifest["outputs"].append(
        fetch_and_write(
            dataset="players",
            path=config.range_file_path("players", "players.parquet"),
            loader=nfl.load_players,
            config=config,
        )
    )

    for dataset, loader in [
        ("rosters", nfl.load_rosters),
        ("rosters_weekly", nfl.load_rosters_weekly),
    ]:
        for season in seasons_for_dataset(seasons, dataset):
            manifest["outputs"].append(
                fetch_and_write(
                    dataset=dataset,
                    season=season,
                    path=config.partitioned_path(dataset, season),
                    loader=lambda season=season, loader=loader: loader(season),
                    config=config,
                )
            )

    if not config.skip_optional:
        for dataset, loader in [
            ("player_stats_weekly", nfl.load_player_stats),
            ("team_stats_weekly", nfl.load_team_stats),
        ]:
            for season in seasons_for_dataset(seasons, dataset):
                manifest["outputs"].append(
                    fetch_and_write(
                        dataset=dataset,
                        season=season,
                        path=config.partitioned_path(dataset, season),
                        loader=lambda season=season, loader=loader: loader(
                            season, summary_level="week"
                        ),
                        config=config,
                    )
                )

        for summary_level in ["reg", "post"]:
            manifest["outputs"].append(
                fetch_and_write(
                    dataset=f"player_stats_{summary_level}",
                    path=config.range_file_path(
                        f"player_stats_season/summary_level={summary_level}",
                        f"player_stats_{summary_level}_{config.start_season}_{config.end_season}.parquet",
                    ),
                    loader=lambda summary_level=summary_level: nfl.load_player_stats(
                        seasons, summary_level=summary_level
                    ),
                    config=config,
                )
            )
            manifest["outputs"].append(
                fetch_and_write(
                    dataset=f"team_stats_{summary_level}",
                    path=config.range_file_path(
                        f"team_stats_season/summary_level={summary_level}",
                        f"team_stats_{summary_level}_{config.start_season}_{config.end_season}.parquet",
                    ),
                    loader=lambda summary_level=summary_level: nfl.load_team_stats(
                        seasons, summary_level=summary_level
                    ),
                    config=config,
                )
            )

    schema_manifest = build_schema_manifest(manifest["outputs"])
    quality_report = validate_outputs(config.out, seasons, config.team_focus, manifest["outputs"])

    write_json(config.manifest_dir / "acquisition_manifest.json", manifest)
    write_json(config.manifest_dir / "schema_manifest.json", schema_manifest)
    write_json(config.manifest_dir / "quality_report.json", quality_report)

    failed_checks = [
        check["name"] for check in quality_report["checks"] if not check.get("passed", False)
    ]
    if failed_checks:
        LOGGER.warning("Quality checks failed: %s", ", ".join(failed_checks))
    else:
        LOGGER.info("All quality checks passed")

    return quality_report
